minecraft_version=1.20.1

# omit the yarn mappings if you want mojmang mappings
#yarn_mappings=1.21.4+build.4

loader_version=0.18.4

# Fabric API
fabric_version=0.92.7+1.20.1

forge_version=1.20.1-47.3.0
#neoforge_version=21.1.219
#yarn_mappings_neoforge_patch=1.21+build.4
